"""add encrypted_ledgers table for sync

Revision ID: 15df943308dd
Revises: 8031778cd009
Create Date: 2026-07-08 01:26:15.054875

"""
from alembic import op
import sqlalchemy as sa


revision = '15df943308dd'
down_revision = '8031778cd009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encrypted_ledgers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('encryption_meta', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encrypted_ledgers')
    # ### end Alembic commands ###
