"""add health_profiles and weight_entries tables

Revision ID: 19165c659b88
Revises: 43fdce381734
Create Date: 2026-07-18 18:41:09.425500

"""
from alembic import op
import sqlalchemy as sa


revision = '19165c659b88'
down_revision = '43fdce381734'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('biological_sex', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('weight_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('recorded_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_entries_recorded_date'), ['recorded_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_weight_entries_recorded_date'))

    op.drop_table('weight_entries')
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_profiles_user_id'))

    op.drop_table('health_profiles')
    # ### end Alembic commands ###
