"""add split_type to shared expenses

Revision ID: 1b8d52a4edb3
Revises: ccfc34337d00
Create Date: 2026-07-10 19:42:54.445555

"""
from alembic import op
import sqlalchemy as sa


revision = '1b8d52a4edb3'
down_revision = 'ccfc34337d00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_expenses', sa.Column('split_type', sa.String(length=20), server_default='equal', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_expenses', 'split_type')
    # ### end Alembic commands ###
