"""add avatar_data to users

Revision ID: 1c404280d0ae
Revises: 1b8d52a4edb3
Create Date: 2026-07-10 21:51:30.319359

"""
from alembic import op
import sqlalchemy as sa


revision = '1c404280d0ae'
down_revision = '1b8d52a4edb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_data')
    # ### end Alembic commands ###
