"""make group created_by nullable, add name snapshot

Revision ID: 43fdce381734
Revises: 0464cbd59ebe
Create Date: 2026-07-17 20:41:56.984476

"""
from alembic import op
import sqlalchemy as sa


revision = '43fdce381734'
down_revision = '0464cbd59ebe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_name_snapshot', sa.String(length=200), nullable=True))
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('created_by_name_snapshot')

    # ### end Alembic commands ###
