"""add email verification

Revision ID: 70bdfef62cb4
Revises: 15df943308dd
Create Date: 2026-07-08 01:56:11.360396

"""
from alembic import op
import sqlalchemy as sa


revision = '70bdfef62cb4'
down_revision = '15df943308dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    # server_default=sa.text('false') is required, not cosmetic: this
    # table already has real rows by the time this migration runs, and
    # a NOT NULL column with no default has nothing to put in those
    # existing rows — Postgres rejects the ALTER outright. SQLite
    # (used for local dev/testing against a fresh, empty database)
    # never surfaces this, which is exactly how this shipped broken
    # the first time. The ORM-level default=False on the User model
    # only applies to NEW rows inserted via SQLAlchemy; it does
    # nothing for rows that already exist when this migration runs.
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
