"""add created_by_email_ref to shared recurring rules

Revision ID: 7c3166c7845f
Revises: cdbda2e18f1f
Create Date: 2026-07-11 12:00:36.562717

"""
from alembic import op
import sqlalchemy as sa


revision = '7c3166c7845f'
down_revision = 'cdbda2e18f1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_recurring_rules', sa.Column('created_by_email_ref', sa.String(length=64), server_default='', nullable=False))
    op.create_index(op.f('ix_shared_recurring_rules_created_by_email_ref'), 'shared_recurring_rules', ['created_by_email_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_recurring_rules_created_by_email_ref'), table_name='shared_recurring_rules')
    op.drop_column('shared_recurring_rules', 'created_by_email_ref')
    # ### end Alembic commands ###
