"""add login events and last_login_at

Revision ID: 8031778cd009
Revises: 3686454547f6
Create Date: 2026-07-08 00:57:09.005043

"""
from alembic import op
import sqlalchemy as sa


revision = '8031778cd009'
down_revision = '3686454547f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_events_created_at'), 'login_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_events_email'), 'login_events', ['email'], unique=False)
    op.create_index(op.f('ix_login_events_user_id'), 'login_events', ['user_id'], unique=False)
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_index(op.f('ix_login_events_user_id'), table_name='login_events')
    op.drop_index(op.f('ix_login_events_email'), table_name='login_events')
    op.drop_index(op.f('ix_login_events_created_at'), table_name='login_events')
    op.drop_table('login_events')
    # ### end Alembic commands ###
