"""add pending group invites

Revision ID: 852ec567450f
Revises: f374779a3ad1
Create Date: 2026-07-10 05:06:48.906196

"""
from alembic import op
import sqlalchemy as sa


revision = '852ec567450f'
down_revision = 'f374779a3ad1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_group_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_group_invites_email'), 'pending_group_invites', ['email'], unique=False)
    op.create_index(op.f('ix_pending_group_invites_group_id'), 'pending_group_invites', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_group_invites_group_id'), table_name='pending_group_invites')
    op.drop_index(op.f('ix_pending_group_invites_email'), table_name='pending_group_invites')
    op.drop_table('pending_group_invites')
    # ### end Alembic commands ###
