"""rename health_profiles biological_sex to gender

Revision ID: 8a2d18560a72
Revises: 9f455e2f8d2e
Create Date: 2026-07-19 23:46:13.248613

"""
from alembic import op
import sqlalchemy as sa


revision = '8a2d18560a72'
down_revision = '9f455e2f8d2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.drop_column('biological_sex')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biological_sex', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
