"""add group_id to settlements

Revision ID: 8bf2b9ffabf1
Revises: 7c3166c7845f
Create Date: 2026-07-14 16:46:04.166194

"""
from alembic import op
import sqlalchemy as sa


revision = '8bf2b9ffabf1'
down_revision = '7c3166c7845f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_settlements_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key('fk_settlements_group_id_groups', 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_settlements_group_id_groups', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_settlements_group_id'))
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
