"""add blood_pressure_entries table

Revision ID: 9d52243a0c62
Revises: 19165c659b88
Create Date: 2026-07-18 19:23:08.083396

"""
from alembic import op
import sqlalchemy as sa


revision = '9d52243a0c62'
down_revision = '19165c659b88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_pressure_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('recorded_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_pressure_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_pressure_entries_recorded_date'), ['recorded_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_blood_pressure_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_pressure_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blood_pressure_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_blood_pressure_entries_recorded_date'))

    op.drop_table('blood_pressure_entries')
    # ### end Alembic commands ###
