"""replace health_profiles date_of_birth with age

Revision ID: 9f455e2f8d2e
Revises: aeca64061761
Create Date: 2026-07-19 22:46:19.720638

"""
from alembic import op
import sqlalchemy as sa


revision = '9f455e2f8d2e'
down_revision = 'aeca64061761'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###
