"""add legal_records table

Revision ID: aeca64061761
Revises: 9d52243a0c62
Create Date: 2026-07-19 01:32:10.937136

"""
from alembic import op
import sqlalchemy as sa


revision = 'aeca64061761'
down_revision = '9d52243a0c62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('record_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('key_date', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('counterparty', sa.String(length=200), nullable=True),
    sa.Column('document_location', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_records_record_type'), ['record_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_legal_records_record_type'))

    op.drop_table('legal_records')
    # ### end Alembic commands ###
