"""add name to pending group invites

Revision ID: ccfc34337d00
Revises: 852ec567450f
Create Date: 2026-07-10 16:24:46.591452

"""
from alembic import op
import sqlalchemy as sa


revision = 'ccfc34337d00'
down_revision = '852ec567450f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_group_invites', sa.Column('name', sa.String(length=200), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_group_invites', 'name')
    # ### end Alembic commands ###
