"""add shared recurring rules

Revision ID: cdbda2e18f1f
Revises: 1c404280d0ae
Create Date: 2026-07-11 03:06:50.388881

"""
from alembic import op
import sqlalchemy as sa


revision = 'cdbda2e18f1f'
down_revision = '1c404280d0ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_recurring_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_by_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), server_default='Other', nullable=False),
    sa.Column('split_type', sa.String(length=20), server_default='equal', nullable=False),
    sa.Column('participant_ids', sa.JSON(), nullable=False),
    sa.Column('pending_participants', sa.JSON(), nullable=False),
    sa.Column('participant_values', sa.JSON(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('last_materialized', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_recurring_rules_group_id'), 'shared_recurring_rules', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_recurring_rules_group_id'), table_name='shared_recurring_rules')
    op.drop_table('shared_recurring_rules')
    # ### end Alembic commands ###
