"""remove health_profiles notes column

Revision ID: f32b916e32ef
Revises: 8a2d18560a72
Create Date: 2026-07-20 02:22:36.099115

"""
from alembic import op
import sqlalchemy as sa


revision = 'f32b916e32ef'
down_revision = '8a2d18560a72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
