"""add category to shared expenses

Revision ID: f374779a3ad1
Revises: 1fb5b7c1cf05
Create Date: 2026-07-10 01:52:01.018161

"""
from alembic import op
import sqlalchemy as sa


revision = 'f374779a3ad1'
down_revision = '1fb5b7c1cf05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_expenses', sa.Column('category', sa.String(length=50), server_default='Other', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shared_expenses', 'category')
    # ### end Alembic commands ###
