"""create recurring_rules table

Revision ID: 076315266561
Revises: fe44e35768e5
Create Date: 2026-08-06

Hand-written, not autogenerated -- same reasoning as the prior
migration in this environment: no network path from this sandbox to
connect to and diff against the live Sanchaydb database. Straightforward
here too: one new table, matching app/models/recurring_rule.py exactly.
"""
from alembic import op
import sqlalchemy as sa


revision = '076315266561'
down_revision = 'fe44e35768e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'recurring_rules',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
        sa.Column('account_id', sa.String(length=36), nullable=False),
        sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column('description', sa.String(length=512), nullable=False),
        sa.Column('category', sa.String(length=128), nullable=True),
        sa.Column('frequency', sa.String(length=16), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('last_materialized', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_recurring_rules_clerk_user_id', 'recurring_rules', ['clerk_user_id'], unique=False)
    op.create_index('ix_recurring_rules_account_id', 'recurring_rules', ['account_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_recurring_rules_account_id', table_name='recurring_rules')
    op.drop_index('ix_recurring_rules_clerk_user_id', table_name='recurring_rules')
    op.drop_table('recurring_rules')
