"""create discussions table

Revision ID: 1b03f752e2e7
Revises: 83d698741ef6
Create Date: 2026-08-07

Hand-written, not autogenerated -- same reasoning as prior migrations
in this environment: no network path from this sandbox to Sanchaydb
to diff against. One new table, matching app/models/discussion.py
exactly.
"""
from alembic import op
import sqlalchemy as sa


revision = '1b03f752e2e7'
down_revision = '83d698741ef6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'discussions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
        sa.Column('title', sa.String(length=256), nullable=False),
        sa.Column('transcript', sa.Text(), nullable=False),
        sa.Column('analysis', sa.JSON(), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_discussions_clerk_user_id', 'discussions', ['clerk_user_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_discussions_clerk_user_id', table_name='discussions')
    op.drop_table('discussions')
