"""add transfer_group_id to transactions

Revision ID: 1f2daada896a
Revises: 1b03f752e2e7
Create Date: 2026-08-07

Hand-written, not autogenerated -- no network path from this sandbox
to Sanchaydb to diff against. One new nullable indexed column, matching
app/models/transaction.py exactly.
"""
from alembic import op
import sqlalchemy as sa


revision = '1f2daada896a'
down_revision = '1b03f752e2e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('transactions', sa.Column('transfer_group_id', sa.String(length=36), nullable=True))
    op.create_index('ix_transactions_transfer_group_id', 'transactions', ['transfer_group_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_transactions_transfer_group_id', table_name='transactions')
    op.drop_column('transactions', 'transfer_group_id')
