"""make description nullable on transactions and recurring_rules

Revision ID: 35d588eb8efb
Revises: 076315266561
Create Date: 2026-08-06

description was NOT NULL on both tables, but the frontend labels this
field "Note (optional)" -- a real mismatch between the stated UX and
the actual constraint, caught via a genuine 422 in production (adding
a Salary transaction with the note left blank). Relaxing the
constraint itself rather than papering over it with a frontend
default substitution, since "optional" was always the intended
behavior, not a fallback to work around.
"""
from alembic import op
import sqlalchemy as sa


revision = '35d588eb8efb'
down_revision = '076315266561'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # batch_alter_table, not plain op.alter_column: SQLite (local
    # dev/test default) doesn't support ALTER COLUMN at all -- batch
    # mode recreates the table under the hood there, and is a
    # transparent no-op translating to a normal ALTER COLUMN on
    # Postgres. render_as_batch=True in env.py only affects
    # autogenerated migrations, not hand-written ones like this --
    # confirmed by this exact migration failing against local SQLite
    # with plain alter_column before this fix.
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.alter_column('description', existing_type=sa.String(length=512), nullable=True)
    with op.batch_alter_table('recurring_rules') as batch_op:
        batch_op.alter_column('description', existing_type=sa.String(length=512), nullable=True)


def downgrade() -> None:
    # Any existing NULL descriptions would need a real value before
    # this could safely revert to NOT NULL -- not attempting a
    # silent backfill here, since inventing placeholder text for rows
    # that legitimately have no description isn't a safe default to
    # choose on someone else's behalf during a downgrade.
    with op.batch_alter_table('recurring_rules') as batch_op:
        batch_op.alter_column('description', existing_type=sa.String(length=512), nullable=False)
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.alter_column('description', existing_type=sa.String(length=512), nullable=False)
