"""create savings_goals table

Revision ID: 4411494155dc
Revises: 35d588eb8efb
Create Date: 2026-08-06

Hand-written, not autogenerated -- same reasoning as prior migrations
in this environment: no network path from this sandbox to Sanchaydb
to diff against. One new table, matching app/models/savings_goal.py
exactly.
"""
from alembic import op
import sqlalchemy as sa


revision = '4411494155dc'
down_revision = '35d588eb8efb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'savings_goals',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column('target_date', sa.Date(), nullable=True),
        sa.Column('account_id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_savings_goals_clerk_user_id', 'savings_goals', ['clerk_user_id'], unique=False)
    op.create_index('ix_savings_goals_account_id', 'savings_goals', ['account_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_savings_goals_account_id', table_name='savings_goals')
    op.drop_index('ix_savings_goals_clerk_user_id', table_name='savings_goals')
    op.drop_table('savings_goals')
