"""add embedding column to transactions

Revision ID: 83d698741ef6
Revises: 4411494155dc
Create Date: 2026-08-07

Hand-written, not autogenerated -- same reasoning as prior migrations
in this environment: no network path from this sandbox to Sanchaydb
to diff against. One new nullable JSON column on transactions, for
Ask Sanchay's retrieval layer (see app/models/transaction.py and
app/services/embedding_service.py for why this is plain JSON, not
pgvector's native Vector type).
"""
from alembic import op
import sqlalchemy as sa


revision = '83d698741ef6'
down_revision = '4411494155dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('transactions', sa.Column('embedding', sa.JSON(), nullable=True))


def downgrade() -> None:
    op.drop_column('transactions', 'embedding')
