"""create accounts, transactions, budgets tables

Revision ID: fe44e35768e5
Revises:
Create Date: 2026-08-02

Hand-written, not autogenerated -- this environment (the sandbox this
was built in) can't reach Neon's network to connect and diff against
the live (empty) Sanchaydb database, so there's nothing for
`alembic revision --autogenerate` to introspect against here. Safe to
hand-write given Sanchaydb is a brand-new, empty database: there's no
existing schema to diff against, no ambiguity about what this
migration needs to do (create these three tables, matching the
SQLAlchemy models in app/models/ exactly), and no risk of
autogenerate's usual failure mode (missing a manual change a previous
migration made that the models don't reflect) since there's no
migration history to diverge from yet.
"""
from alembic import op
import sqlalchemy as sa


revision = 'fe44e35768e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'accounts',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('type', sa.String(length=32), nullable=False),
        sa.Column('starting_balance', sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_accounts_clerk_user_id', 'accounts', ['clerk_user_id'], unique=False)

    op.create_table(
        'transactions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
        sa.Column('account_id', sa.String(length=36), nullable=False),
        sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column('description', sa.String(length=512), nullable=False),
        sa.Column('category', sa.String(length=128), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_transactions_clerk_user_id', 'transactions', ['clerk_user_id'], unique=False)
    op.create_index('ix_transactions_account_id', 'transactions', ['account_id'], unique=False)
    op.create_index(
        'ix_transactions_clerk_user_id_date', 'transactions', ['clerk_user_id', 'date'], unique=False
    )

    op.create_table(
        'budgets',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
        sa.Column('category', sa.String(length=128), nullable=False),
        sa.Column('monthly_limit', sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_budgets_clerk_user_id', 'budgets', ['clerk_user_id'], unique=False)
    op.create_index(
        'ux_budgets_clerk_user_id_category', 'budgets', ['clerk_user_id', 'category'], unique=True
    )


def downgrade() -> None:
    op.drop_index('ux_budgets_clerk_user_id_category', table_name='budgets')
    op.drop_index('ix_budgets_clerk_user_id', table_name='budgets')
    op.drop_table('budgets')

    op.drop_index('ix_transactions_clerk_user_id_date', table_name='transactions')
    op.drop_index('ix_transactions_account_id', table_name='transactions')
    op.drop_index('ix_transactions_clerk_user_id', table_name='transactions')
    op.drop_table('transactions')

    op.drop_index('ix_accounts_clerk_user_id', table_name='accounts')
    op.drop_table('accounts')
