import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


def _now() -> datetime:
    return datetime.now(timezone.utc)


class SharedExpenseComment(Base):
    """
    Doubles as two things deliberately, rather than building two
    separate tables: the discussion thread ("I don't think I had a
    drink, can we adjust?") AND the edit-history log. is_system=True
    rows are auto-generated by the service layer whenever an edit
    happens ("Bob changed the amount from $40.00 to $35.00"); regular
    comments have is_system=False. Interleaving both in one
    chronological feed is a genuine UX choice, not just a schema
    shortcut — system events and human commentary about THIS SAME
    dispute belong in the same timeline, the way GitHub interleaves
    issue comments with label/assignment changes.
    """

    __tablename__ = "shared_expense_comments"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    shared_expense_id: Mapped[str] = mapped_column(String(36), ForeignKey("shared_expenses.id"), nullable=False, index=True)
    user_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    name_snapshot: Mapped[str] = mapped_column(String(200), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    is_system: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
